project_id = "spatial-ship-354209"
sa="dataproc-cluster-sa"
network = "df-network"
sub_network = "df-subnetwork"
region = "us-central1"
df_instance = "data-fusion-private-instance"
edition = "BASIC"
private_ip_range = "10.20.0.0/14"
label_value = "example_value"
enable_logging = true 
df_version= "6.5.1"
private_instance=true
