project_id = "spatial-ship-354209"
sa="dataproc-cluster-sa"
/*network = "wf-us-prod-vpc-app01"
sub_network = "wf-us-prod-vpc-app01-subnet1"*/
region = "us-central1"
df_instance = "wf-us-prod-cdf-app01-res123"
edition = "BASIC"
private_ip_range = "10.20.0.0/14"
label_value = "example_value"
enable_logging = true 
df_version= "6.5.1"
private_instance=true
